import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {CONSENT_KEY,createAnalyticsController,safeSearchTerm} from '../src/lib/analytics.mjs';

function fixture(id='G-L37H8G797Y'){
 const values=new Map();const scripts=[];
 const window={localStorage:{getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value)}};
 const document={head:{append:script=>scripts.push(script)},createElement:()=>({dataset:{}}),querySelector:selector=>selector==='[data-acquisition-ga]'?scripts[0]:null};
 const analytics=createAnalyticsController({window,document,measurementId:id});
 return {values,scripts,window,analytics};
}

test('absent configuration disables analytics cleanly',()=>{const f=fixture('');assert.equal(f.analytics.enabled,false);assert.equal(f.analytics.setChoice('granted'),true);assert.equal(f.analytics.load(),false);assert.equal(f.scripts.length,0);});
test('no Google script before consent or after denial; choice persists',()=>{const f=fixture();assert.equal(f.analytics.choice(),null);assert.equal(f.analytics.load(),false);assert.equal(f.scripts.length,0);assert.equal(f.analytics.setChoice('denied'),true);assert.equal(f.values.get(CONSENT_KEY),'denied');assert.equal(f.analytics.load(),false);assert.equal(f.scripts.length,0);assert.equal(f.analytics.track('course_start'),false);});
test('grant loads direct gtag once and emits conservative events',()=>{const f=fixture();f.analytics.setChoice('granted');assert.equal(f.scripts.length,1);assert.match(f.scripts[0].src,/^https:\/\/www\.googletagmanager\.com\/gtag\/js\?id=G-L37H8G797Y$/);assert.equal(f.analytics.load(),false);assert.equal(f.scripts.length,1);assert.deepEqual(Array.from(f.window.dataLayer[1]),['config','G-L37H8G797Y',{allow_google_signals:false,allow_ad_personalization_signals:false}]);assert.equal(f.analytics.track('lesson_complete',{lesson_slug:'example',lesson_title:'Example',module:1}),true);assert.equal(f.analytics.track('course_start'),true);assert.equal(f.analytics.track('source_video_click',{video_id:'abc',source_collection:'yusufa-sey'}),true);assert.equal(f.analytics.track('site_search',{search_term:'seller financing'}),true);assert.deepEqual(f.window.dataLayer.slice(2).map(x=>x[1]),['lesson_complete','course_start','source_video_click','site_search']);});
test('revoking consent stops events and GA beacons immediately',()=>{const f=fixture();f.analytics.setChoice('granted');f.analytics.setChoice('denied');assert.equal(f.window['ga-disable-G-L37H8G797Y'],true);assert.equal(f.analytics.track('course_start'),false);assert.equal(f.analytics.choice(),'denied');});
test('blocked localStorage still lets a visitor dismiss the banner for this page',()=>{const f=fixture();Object.defineProperty(f.window,'localStorage',{get(){throw new Error('blocked');}});assert.equal(f.analytics.choice(),null);assert.equal(f.analytics.setChoice('denied'),true);assert.equal(f.analytics.choice(),'denied');assert.equal(f.scripts.length,0);});
test('only known educational topics are sent as search terms',()=>{assert.equal(safeSearchTerm('  direct   lending '),'direct lending');for(const term of ['person@example.com','https://example.com','www.example.com','555-123-4567','123456789','Alice Smith'])assert.equal(safeSearchTerm(term),'');const f=fixture();f.analytics.setChoice('granted');assert.equal(f.analytics.track('site_search',{search_term:'person@example.com'}),true);assert.deepEqual(Array.from(f.window.dataLayer.at(-1)),['event','site_search',{}]);});
test('AI events retain only safe mode, synthetic case, difficulty, and completion metadata',()=>{const f=fixture();f.analytics.setChoice('granted');const privateText='customer payroll, forecast, or prompt';f.analytics.track('ai_question',{mode:'ask_course',question:privateText,response:privateText,amount:420000,company_name:'Acme'});f.analytics.track('deal_lab_complete',{case_id:'bluejay-field-services',difficulty:'beginner',completion_status:'complete',transcript:privateText});const events=f.window.dataLayer.slice(2).map(item=>Array.from(item));assert.deepEqual(events,[['event','ai_question',{mode:'ask_course'}],['event','deal_lab_complete',{case_id:'bluejay-field-services',difficulty:'beginner',completion_status:'complete'}]]);assert.equal(JSON.stringify(events).includes(privateText),false);});
test('integration case uses only the existing consent-gated synthetic-case metadata contract',()=>{const f=fixture();assert.equal(f.analytics.track('deal_lab_start',{case_id:'two-companies-one-team'}),false);f.analytics.setChoice('granted');f.analytics.track('deal_lab_start',{case_id:'two-companies-one-team',difficulty:'advanced',prompt:'private text',response:'private text'});assert.deepEqual(Array.from(f.window.dataLayer.at(-1)),['event','deal_lab_start',{case_id:'two-companies-one-team',difficulty:'advanced'}]);});
test('CSP allows only GA endpoints and preserves security directives',()=>{const csp=fs.readFileSync('public/_headers','utf8');for(const host of ['https://www.googletagmanager.com','https://*.google-analytics.com','https://*.google.com'])assert.ok(csp.includes(host));for(const token of ["object-src 'none'","frame-ancestors 'none'",'X-Content-Type-Options: nosniff','Referrer-Policy: strict-origin-when-cross-origin','Permissions-Policy:'])assert.ok(csp.includes(token));for(const host of ['doubleclick.net','googleadservices.com','googlesyndication.com'])assert.equal(csp.includes(host),false);});
