import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const read=name=>JSON.parse(fs.readFileSync(new URL(`../src/data/${name}.json`,import.meta.url),'utf8'));
const contract=JSON.parse(fs.readFileSync(new URL('../docs/content-contract.json',import.meta.url),'utf8'));
const topicIds=new Set(contract.topics);const videos=read('videos'),evidence=read('evidence'),numbers=read('numbers'),providers=read('providers');const ids=new Set(videos.map(x=>x.id));
test('complete source inventory preserves original IDs and URLs',()=>{assert.equal(videos.length,117);assert.equal(ids.size,117);for(const v of videos){assert.equal(v.url,`https://www.youtube.com/watch?v=${v.id}`);assert.ok(v.title);assert.ok(v.summary);}});
test('quantitative and provider references have complete source relationships',()=>{for(const [records,count] of [[evidence,243],[numbers,313],[providers,28]]){assert.equal(records.length,count);assert.equal(new Set(records.map(x=>x.id)).size,count);for(const r of records){assert.ok(r.videoIds.length>0,r.id);for(const id of r.videoIds)assert.ok(ids.has(id),`${r.id}: ${id}`);for(const topic of r.topics)assert.ok(topicIds.has(topic),`${r.id}: ${topic}`);}}});
test('public projections never contain internal metadata or raw supporting context',()=>{for(const name of ['videos','evidence','numbers','providers']){const text=JSON.stringify(read(name));assert.doesNotMatch(text,/source_file|sourceFile|supporting_context|supportingContext|\/Users\/|whisper_corpus\/|Videos_part\d\.md|Whisper repetition collapsed/i,name);}});
test('uncertain numerical and provider records keep explicit cautions',()=>{for(const r of [...numbers,...providers])if(r.confidence==='low')assert.ok(r.caution.length>15,r.id);});
test('every topic and lesson source relation resolves',()=>{for(const kind of ['lessons','topics','examples'])for(const file of fs.readdirSync(new URL(`../src/content/${kind}/`,import.meta.url)).filter(x=>x.endsWith('.md'))){const text=fs.readFileSync(new URL(`../src/content/${kind}/${file}`,import.meta.url),'utf8');const yaml=text.split('---')[1];const getArray=key=>{const match=yaml.match(new RegExp(`^${key}:\\s*(\\[[^\\n]+\\])`,'m'));if(match){try{return JSON.parse(match[1]);}catch{}}return null;};for(const id of getArray('sources')||[])assert.ok(ids.has(id),`${file} source ${id}`);for(const id of getArray('evidence')||[])assert.ok(evidence.some(x=>x.id===id),`${file} evidence ${id}`);for(const t of getArray('topics')||getArray('related')||[])assert.ok(topicIds.has(t),`${file} topic ${t}`);}});
