import {chromium} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';import assert from 'node:assert/strict';import fs from 'node:fs';
const base=process.env.PREVIEW_URL||'http://127.0.0.1:4321';fs.mkdirSync('artifacts',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const routes=['/','/start-here/','/course/','/course/understanding-private-credit/','/topics/private-credit/','/financing/','/numbers/','/providers/','/sources/yusufa-sey/','/glossary/','/about/','/methodology/','/search/'];
const audits=[];
for(const route of routes){const response=await page.goto(base+route);assert.equal(response.status(),200,route);await page.waitForLoadState('networkidle');assert.equal(await page.locator('h1').count(),1,route);const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();const violations=results.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.slice(0,3).map(n=>n.target)}));audits.push({route,violations});}
// Editorial regressions: brand, unique definitions, correct labels and useful failure paths.
await page.goto(base+'/');assert.match(await page.title(),/Acquisition Companion/);assert.equal(await page.locator('meta[name=description]').getAttribute('content'),'The free, source-linked guide to buying, financing, and building businesses.');
await page.goto(base+'/topics/private-credit/');assert.equal(await page.locator('.page-header p').count(),1);assert.equal(await page.locator('.related a[href="/topics/private-credit/"]').count(),0);
await page.goto(base+'/sources/yusufa-sey/');assert.equal(await page.locator('label[for=filter-kind]').textContent(),'Coverage');
await page.route('**/pagefind/pagefind-ui.js',route=>route.abort());await page.goto(base+'/search/');assert.equal(await page.locator('#search-fallback').isVisible(),true);assert.match(await page.locator('#search-status').textContent(),/could not load/);assert.equal(await page.locator('#search-fallback a').count(),3);await page.unroute('**/pagefind/pagefind-ui.js');
await page.goto(base+'/');await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').textContent(),'Skip to content');await page.screenshot({path:'artifacts/home-desktop.png',fullPage:true});
await page.goto(base+'/numbers/');await page.locator('#filter-query').fill('receivables');assert.match(await page.locator('[data-result-count]').innerText(),/\d+ of 313/);const filtered=await page.locator('[data-filter-item]:visible').count();assert.ok(filtered>0 && filtered<313);await page.locator('#filter-query').fill('zxq-no-such-financial-record');assert.equal(await page.locator('[data-filter-item]:visible').count(),0);assert.equal(await page.locator('[data-empty-state]').isVisible(),true);await page.getByRole('button',{name:'Clear filters'}).click();await page.waitForFunction(()=>document.querySelector('[data-result-count]').textContent==='313 of 313 records');
await page.goto(base+'/course/acquisition-entrepreneurship/');await page.locator('#lesson-complete').check();await page.reload();assert.equal(await page.locator('#lesson-complete').isChecked(),true);await page.goto(base+'/course/');assert.match(await page.locator('[data-progress-status]').innerText(),/1 of 20/);await page.getByRole('button',{name:'Reset progress'}).click();assert.match(await page.locator('[data-progress-status]').innerText(),/0 of 20/);
await page.goto(base+'/search/');await page.locator('.pagefind-ui__search-input').fill('private credit');await page.waitForSelector('.pagefind-ui__result-link');assert.ok(await page.locator('.pagefind-ui__result-link').count()>0);assert.match(await page.locator('#search').innerText(),/private credit/i);await page.screenshot({path:'artifacts/search-desktop.png',fullPage:true});
for(const viewport of [{width:390,height:844},{width:768,height:1024}]){await page.setViewportSize(viewport);for(const route of ['/','/course/','/course/understanding-private-credit/','/numbers/','/topics/private-credit/','/sources/yusufa-sey/']){await page.goto(base+route);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),`${route} horizontal overflow ${viewport.width}`);}await page.goto(base+'/');await page.screenshot({path:`artifacts/home-${viewport.width}.png`,fullPage:true});}
const denied=await browser.newContext();await denied.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Storage denied','SecurityError');}});});const dp=await denied.newPage();await dp.goto(base+'/course/acquisition-entrepreneurship/');assert.equal(await dp.locator('#lesson-complete').isDisabled(),true);assert.match(await dp.locator('[data-progress-status]').innerText(),/unavailable/);await denied.close();
const nojs=await browser.newContext({javaScriptEnabled:false});const np=await nojs.newPage();await np.goto(base+'/numbers/');assert.equal(await np.locator('[data-filter-item]').count(),313);assert.match(await np.locator('noscript').innerText(),/All records remain readable/);await np.setViewportSize({width:390,height:844});await np.goto(base+'/course/understanding-private-credit/');assert.equal(await np.locator('.lesson-sidebar details').getAttribute('open'),null);assert.equal(await np.locator('.primary-nav').evaluate(el=>el.scrollWidth<=el.clientWidth+1),true);await np.screenshot({path:'artifacts/lesson-mobile-nojs.png',fullPage:true});await nojs.close();
await browser.close();const violations=audits.flatMap(a=>a.violations.map(v=>({route:a.route,...v})));const result={routesAudited:routes.length,accessibilityViolations:violations,browserErrors:errors,filters:'passed',progress:'passed',storageDenied:'passed',noJavaScript:'passed',pagefindSearch:'passed',responsive:[390,768,1440]};fs.writeFileSync('artifacts/browser-validation.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));assert.equal(errors.length,0,'Browser errors');assert.equal(violations.length,0,'Accessibility violations');
